version: "3.7"
services:
  app:
    build:
      args:
        user: dolly
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: apilaravel
    container_name: apilaravel-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 6001:6001
    volumes:
      - ./:/var/www
    networks:
      - apilaravel

  db:
    image: mysql:latest
    container_name: apilaravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - apilaravel

  nginx:
    image: nginx:alpine
    container_name: apilaravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - apilaravel
  dbadmin:
    container_name: apilaravel-dbadminer
    hostname: dbadmin
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - apilaravel
    restart: unless-stopped

networks:
  apilaravel:
    driver: bridge